services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    container_name: taskapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskapi_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB: ${DB}
      ENV: dev
    networks:
      - taskapi_network

volumes:
  mysql_data:
    name: taskapi_mysql_volume

networks:
  taskapi_network:
    name: taskapi_network
    driver: bridge
